name: Documentation

on:
  push:
    branches: [main]
    paths:
      - spice-docs.json
      - "**/*.md"
      - "**/*.go"
      - "docs/**"
      - "profile/**"
      - "store/assets/**"
  pull_request:
    branches: [main]
    paths:
      - spice-docs.json
      - "**/*.md"
      - "**/*.go"
      - "docs/**"
      - "profile/**"
      - "store/assets/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  documentation:
    uses: spice-framework/.github/.github/workflows/docs-source.yml@10708a97229539acd7be60378977b0506dd67d76
    with:
      docs_commit: 8cf89e57e01b67498e66eb262df872a537b6abe6
